#-----------------------------#
#     Major Site Settings     #
#-----------------------------#
url: http://digrastudents.org
domain: digrastudents.org
title: digrastudents.org
description: "Home page of the Digital Gaming Research Assocation (DiGRA) Student Representatives"
author:
  name: DiGRA Student Representatives
  facebook: digrastudents
  twitter: digrastudents
analytics:
  provider: google
  google:
    tracking_id: 'UA-32704915-1'
rsync:
  user: digrastu
  host: digrastudents.org
  path: ~/public_html/

#---------------------------------------#
#             Blog Settings             #
#---------------------------------------#
paginate: 10                            # Posts per page on the blog index
paginate_path: "blog/page:num"
pagination_dir: blog                    # Directory base for pagination URLs, e.g., /blog/page/2/
permalink: /blog/:title                 # URL structure for blog posts
recent_posts: 5                         # Posts in the sidebar Recent Posts section
excerpt_link: "Continue reading &rarr;" # "Continue reading" link text at the bottom of excerpted articles
category_dir: blog/categories           # Directory base for category URLs, e.g., /blog/categories/
tag_dir: blog/tags                      # Directory base for tag URLs, e.g., /blog/tags/

#-----------------------------#
#       Jekyll Settings       #
#-----------------------------#
source: src
destination: public
pygments: true
markdown: kramdown
relative_permalinks: true

#-----------------------------#
#       Build Settings        #
#-----------------------------#
include: [".htaccess"]
exclude: [
  "resolutionizr.html",
  "scss"
]
js: [
  "games-research-articles.min.js": [
    "libs/jquery.dataTables.js",
    "libs/jquery.searchPolyfill.js",
    "_games-research-articles.js"
  ],
  "games-research-journals.min.js": [
    "libs/jquery.dataTables.js",
    "libs/jquery.searchPolyfill.js",
    "_games-research-journals.js"
  ],
  "games-research-positions.min.js": [
    "libs/jquery.dataTables.js",
    "libs/jquery.searchPolyfill.js",
    "_games-research-positions.js"
  ],
  "games-research-twitter.min.js": [
    "libs/jquery.dataTables.js",
    "libs/jquery.searchPolyfill.js",
    "_games-research-twitter.js"
  ],
  "site.min.js": [
    "libs/sprintf.min.js",
    "libs/ba-linkify.min.js",
    "libs/bootstrap-transition.js",
    "libs/bootstrap-collapse.js",
    "libs/bootstrap-tooltip.js",
    "libs/imageFlip.js",
    "libs/jquery.cookie.js",
    "libs/jquery.fcbkcomplete.js",
    "libs/jquery.notifier.js",
    "libs/jquery.showLoading.js",
    "libs/jquery.treemap.js",
    "libs/jquery.validate.js",
    "libs/fayer.js",
    "_digrastudents.js"
  ]
]
